### ISSUE TITLE
Update materials by Anna

### ISSUE THREAD

**Issue by deSagaz** [utrecht-time-machine/utm-client#16]
- [x] Drogisterij Woortman document
  - [x] Translation of ad
  - [x] New document
- [x] De Beurs document
- [x] De Liefde's Centraal Apotheek
  - [x] New audio recording
  - [x] New document
- [x] Public Restroom
- [x] Extended articles
  - [x] Drogisterij Woortman
  - [x] De Beurs
  - [x] De Liefde's Centraal Apotheek

See e-mail for details (subject: `Short 'app' versions of my walking tour texts + audio`)

**Comment by deSagaz** [comment]
@Simon-Dirks , I'll take a look at updating this and Nayra's texts as well.

**Comment by Simon-Dirks** [comment]
> @Simon-Dirks , I'll take a look at updating this and Nayra's texts as well.

Since Toine asked me personally, I couldn't resist!

**Comment by deSagaz** [comment]
Well, I can't complain - thanks for looking into it!
