### ISSUE TITLE
Fix audio fragments on mobile

### ISSUE THREAD

**Issue by deSagaz** [utrecht-time-machine/utm-client#17]
Audio works on desktop browsers, but not in mobile. We'll need to check the console output on mobile devices.

**Comment by deSagaz** [comment]
It works on Android (Chrome), but not iOS Safari/Firefox. Needs further looking into...

**Comment by Simon-Dirks** [comment]
Don't we get a free [BrowserStack](https://www.browserstack.com/) subscription in the GitHub Student Developer Pack? Might help us out.

**Comment by Simon-Dirks** [comment]
Probably fixed by now, switched from ngx-audio-player to [Videogular2](https://github.com/videogular/videogular2) (supported by JetBrains!), because I ran into some other issues with the ngx-audio-player as well.
