### ISSUE TITLE
FAB in explore view throws error if no story is available or user did not swipe first

### ISSUE THREAD

**Issue by deSagaz** [utrecht-time-machine/utm-client#4]
![image](https://user-images.githubusercontent.com/4922048/67905966-738de280-fb73-11e9-89d2-edf004a0bde3.png)

**Comment by deSagaz** [comment]
The FAB button may also be replaced with a simple press on the card itself, to increase simplicity. What do you think?

**Comment by Simon-Dirks** [comment]
Wanted to add this bug yesterday as well, and had the exact same thoughts about pressing the cards instead of the fab button. Makes a lot more sense for now.
